name: rfa_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - pandas
  - tqdm
  - librosa
  - pydub
  - ffmpeg
  - pyworld
  - pysoundfile
  - optuna
  - pip
  - pip:
      - soundfile  
      - shap 
      - numba 
